version: '3'

services:
  web:
    build: ./web
    volumes:
      - ./web:/usr/src/app
    ports:
      - 8001:3001
    links:
      - api

  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 8002:3000